FROM skilldlabs/frontend:latest

MAINTAINER Andy Postnikov

RUN npm install -g \
  breakpoint-sass \
  browser-sync \
  chroma-sass \
  del \
  eslint \
  gulp-autoprefixer \
  gulp-eslint \
  gulp-if \
  gulp-load-plugins \
  gulp-rename \
  gulp-replace \
  gulp-sass-lint \
  gulp-size \
  gulp-sourcemaps \
  kss \
  node-sass-import-once \
  sass-lint \
  support-for \
  typey \
  zen-grids

COPY docker-entrypoint.sh /usr/bin/
